# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
sudo: required
dist: trusty

r_packages:
  - covr

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov(token = "6e978497-c837-416a-b5e1-ddd4dd676fb5")'
